services:
  - type: web
    name: onthebluff
    runtime: node
    plan: starter
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: onthebluff-db
          property: connectionString
      - key: SESSION_SECRET
        sync: false
      - key: PORT
        value: 10000

databases:
  - name: onthebluff-db
    databaseName: onthebluff
    plan: starter
