services:
  - type: web
    name: onthebluff
    runtime: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: NODE_ENV=production node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: onthebluff-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: PORT
        value: 10000

databases:
  - name: onthebluff-db
    databaseName: onthebluff
    plan: starter
